engine:
  type: "in_memory"
network:
  address: "127.0.0.1:3223"
  max_connections: 1
  max_message_size: 4096
  idle_timeout: 10s
logging:
  level: "debug"
  output: "./output.log"
mode: "tcp"